#!/usr/bin/env python3
"""Validate autogenerated README paper sections for structure and data quality."""

from __future__ import annotations

import argparse
import re
from dataclasses import dataclass
from pathlib import Path
from typing import Dict, List, Sequence, Tuple
from urllib.parse import urlparse

CATEGORY_MARKERS = [
    "SEGMENTATION",
    "RECONSTRUCTION",
    "CLASSIFICATION",
    "IMAGE_REGISTRATION",
    "DOMAIN_ADAPTATION",
    "GENERATIVE_MODELS",
    "GENERAL",
]

ALLOWED_CODE_HOSTS = {"github.com", "gitlab.com", "huggingface.co"}
COVERAGE_BLOCK_PATTERN = re.compile(
    r"<!-- BEGIN COVERAGE_REPORT -->(?P<body>.*?)<!-- END COVERAGE_REPORT -->", re.S
)
SCOPE_LINE_PATTERN = re.compile(r"^\*\*Conference Scope\*\*: (?P<scope>.+)$", re.M)
MODE_LINE_PATTERN = re.compile(r"^\*\*Discovery Mode\*\*: (?P<mode>.+)$", re.M)

ENTRY_PATTERN = re.compile(
    r"^\* \*\*\[(?P<title>.+?)\]\((?P<arxiv>https?://arxiv\.org/abs/\d{4}\.\d{4,5}(?:v\d+)?)\)\*\* - "
    r"\[Code\]\((?P<code>https?://[^\s)]+)\)(?P<extra>.*)$"
)
EXTRA_CODE_PATTERN = re.compile(r"\[Code\d+\]\((https?://[^\s)]+)\)")
CONFIDENCE_PATTERN = re.compile(r"\(confidence:\s*(high|medium)\)")
SUMMARY_CATEGORY_ROW_PATTERN = re.compile(r"^\|\s*(?P<category>[^|]+)\|\s*(?P<count>\d+)\s*\|\s*(?P<gap>\d+)\s*\|$")


@dataclass
class ParsedEntry:
    marker: str
    title: str
    arxiv_url: str
    code_links: List[str]


def _normalize_host(host: str) -> str:
    host = host.lower()
    return host[4:] if host.startswith("www.") else host


def _valid_code_url(url: str) -> bool:
    if "}{" in url:
        return False

    parsed = urlparse(url)
    if parsed.scheme not in {"http", "https"}:
        return False

    host = _normalize_host(parsed.netloc)
    if host not in ALLOWED_CODE_HOSTS:
        return False

    segments = [segment for segment in parsed.path.split("/") if segment]
    return len(segments) >= 2


def _extract_category_block(readme: str, marker: str) -> str:
    pattern = re.compile(rf"<!-- BEGIN {marker}_PAPERS -->(?P<body>.*?)<!-- END {marker}_PAPERS -->", re.S)
    matches = list(pattern.finditer(readme))
    if len(matches) != 1:
        raise ValueError(f"Marker block for {marker} must appear exactly once")
    return matches[0].group("body")


def _parse_entries(marker: str, block: str) -> List[ParsedEntry]:
    entries: List[ParsedEntry] = []

    for raw_line in block.splitlines():
        line = raw_line.strip()
        if not line:
            continue
        if not line.startswith("* "):
            raise ValueError(f"{marker}: unexpected non-bullet content: {line}")

        match = ENTRY_PATTERN.match(line)
        if not match:
            raise ValueError(f"{marker}: malformed entry: {line}")

        code_links = [match.group("code")]
        code_links.extend(EXTRA_CODE_PATTERN.findall(match.group("extra")))

        entries.append(
            ParsedEntry(
                marker=marker,
                title=match.group("title").strip(),
                arxiv_url=match.group("arxiv"),
                code_links=code_links,
            )
        )

    return entries


def validate_readme_text(readme: str) -> List[str]:
    errors: List[str] = []
    all_entries: List[ParsedEntry] = []

    for marker in CATEGORY_MARKERS:
        try:
            block = _extract_category_block(readme, marker)
            entries = _parse_entries(marker, block)
            all_entries.extend(entries)
        except ValueError as exc:
            errors.append(str(exc))

    seen_in_category: Dict[Tuple[str, str], str] = {}
    arxiv_to_title: Dict[str, str] = {}

    for entry in all_entries:
        per_category_key = (entry.marker, entry.arxiv_url)
        if per_category_key in seen_in_category:
            errors.append(
                f"{entry.marker}: duplicate arXiv entry {entry.arxiv_url} (" f"{entry.title})"
            )
        else:
            seen_in_category[per_category_key] = entry.title

        previous_title = arxiv_to_title.get(entry.arxiv_url)
        if previous_title and previous_title != entry.title:
            errors.append(
                "arXiv entry mapped to multiple titles: "
                f"{entry.arxiv_url} -> '{previous_title}' vs '{entry.title}'"
            )
        else:
            arxiv_to_title[entry.arxiv_url] = entry.title

        seen_code = set()
        for code_url in entry.code_links:
            if not _valid_code_url(code_url):
                errors.append(f"{entry.marker}: invalid or unsupported code URL {code_url}")
            if code_url in seen_code:
                errors.append(f"{entry.marker}: duplicated code URL in one entry {code_url}")
            seen_code.add(code_url)

    # Enforce confidence tags in each non-empty category line.
    for marker in CATEGORY_MARKERS:
        try:
            block = _extract_category_block(readme, marker)
        except ValueError:
            continue
        for raw_line in block.splitlines():
            line = raw_line.strip()
            if not line:
                continue
            if line.startswith("* ") and not CONFIDENCE_PATTERN.search(line):
                errors.append(f"{marker}: missing confidence tag in entry: {line}")

    scope_match = SCOPE_LINE_PATTERN.search(readme)
    mode_match = MODE_LINE_PATTERN.search(readme)
    if not scope_match:
        errors.append("Missing '**Conference Scope**' metadata line")
    if not mode_match:
        errors.append("Missing '**Discovery Mode**' metadata line")

    coverage_match = COVERAGE_BLOCK_PATTERN.search(readme)
    if not coverage_match:
        errors.append("Missing coverage report block markers")
        return errors

    coverage_body = coverage_match.group("body")
    row_counts: Dict[str, int] = {}
    for raw_line in coverage_body.splitlines():
        line = raw_line.strip()
        match = SUMMARY_CATEGORY_ROW_PATTERN.match(line)
        if not match:
            continue
        category = match.group("category").strip()
        row_counts[category] = int(match.group("count"))
        expected_gap = max(0, 1000 - int(match.group("count")))
        if int(match.group("gap")) != expected_gap:
            errors.append(f"Coverage gap mismatch for '{category}': expected {expected_gap}")

    if len(row_counts) != len(CATEGORY_MARKERS):
        errors.append("Coverage report must include exactly one row per category")
        return errors

    marker_to_name = {
        "SEGMENTATION": "Segmentation",
        "RECONSTRUCTION": "Reconstruction",
        "CLASSIFICATION": "Classification",
        "IMAGE_REGISTRATION": "Image Registration",
        "DOMAIN_ADAPTATION": "Domain Adaptation",
        "GENERATIVE_MODELS": "Generative Models",
        "GENERAL": "General",
    }

    for marker, category_name in marker_to_name.items():
        try:
            block = _extract_category_block(readme, marker)
        except ValueError:
            continue
        count = sum(1 for ln in block.splitlines() if ln.strip().startswith("* "))
        reported = row_counts.get(category_name)
        if reported is None:
            errors.append(f"Coverage report missing category '{category_name}'")
            continue
        if count != reported:
            errors.append(
                f"Coverage count mismatch for '{category_name}': report={reported}, actual={count}"
            )

    return errors


def run_validation(readme_path: str) -> int:
    readme = Path(readme_path).read_text(encoding="utf-8")
    errors = validate_readme_text(readme)

    if errors:
        print("README validation failed with the following issues:")
        for error in errors:
            print(f"- {error}")
        return 1

    print("README validation passed")
    return 0


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Validate autogenerated README sections")
    parser.add_argument("--readme", default="README.md", help="Path to README markdown file")
    args = parser.parse_args(argv)

    return run_validation(args.readme)


if __name__ == "__main__":
    raise SystemExit(main())
